import { supabase } from './supabase';

export interface KamiDocument {
  id: string;
  student_id: string;
  week_number: number;
  day_number: number;
  kami_document_id: string;
  kami_share_url: string;
  created_at: string;
}

/**
 * Check if Kami API is configured
 */
export function isKamiConfigured(): boolean {
  return !!import.meta.env.VITE_KAMI_API_KEY;
}

/**
 * Convert text to PDF blob using jsPDF
 */
async function textToPDF(
  studentName: string,
  text: string,
  week: number,
  day: number,
  activityQuestion?: string
): Promise<Blob> {
  // Dynamically import jsPDF to reduce bundle size
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Beyond The Game', margin, 20);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`Student: ${studentName}`, margin, 32);

  doc.setFontSize(12);
  doc.text(`Week ${week} - Module ${day}`, margin, 42);
  doc.text(`Submitted: ${new Date().toLocaleDateString()}`, margin, 50);

  // Separator line
  doc.setLineWidth(0.5);
  doc.line(margin, 55, pageWidth - margin, 55);

  // Activity question (if provided)
  let yPosition = 65;

  if (activityQuestion) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Assignment:', margin, yPosition);
    yPosition += 8;

    doc.setFont('helvetica', 'italic');
    const questionLines = doc.splitTextToSize(activityQuestion, contentWidth);
    doc.text(questionLines, margin, yPosition);
    yPosition += (questionLines.length * 6) + 10;
  }

  // Student response
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Response:', margin, yPosition);
  yPosition += 8;

  doc.setFont('helvetica', 'normal');
  const responseLines = doc.splitTextToSize(text, contentWidth);

  // Handle multi-page if needed
  const lineHeight = 6;
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxY = pageHeight - margin;

  for (const line of responseLines) {
    if (yPosition > maxY) {
      doc.addPage();
      yPosition = margin;
    }
    doc.text(line, margin, yPosition);
    yPosition += lineHeight;
  }

  // Footer on last page
  const footerY = pageHeight - 10;
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text('Generated by Beyond The Game Financial Literacy Platform', margin, footerY);

  return doc.output('blob');
}

/**
 * Create a Kami document from student writing
 * Note: This requires Kami API access. If not available, returns a local PDF download URL.
 */
export async function createKamiDocument(
  studentId: string,
  studentName: string,
  assignmentText: string,
  weekNumber: number,
  dayNumber: number,
  activityQuestion?: string
): Promise<{ documentId: string; shareUrl: string; isLocal?: boolean }> {
  const apiKey = import.meta.env.VITE_KAMI_API_KEY;

  // Generate PDF
  const pdf = await textToPDF(studentName, assignmentText, weekNumber, dayNumber, activityQuestion);

  if (!apiKey) {
    // Fallback: Create local blob URL for download/preview
    console.warn('Kami API key not configured - using local PDF');
    const blobUrl = URL.createObjectURL(pdf);

    return {
      documentId: `local_${studentId}_${weekNumber}_${dayNumber}_${Date.now()}`,
      shareUrl: blobUrl,
      isLocal: true
    };
  }

  try {
    // Upload to Kami
    const formData = new FormData();
    formData.append('file', pdf, `${studentName}_Week${weekNumber}_Module${dayNumber}.pdf`);
    formData.append('name', `${studentName} - Week ${weekNumber} Module ${dayNumber}`);

    const response = await fetch('https://api.kamiapp.com/api/documents', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
      },
      body: formData
    });

    if (!response.ok) {
      throw new Error(`Kami API error: ${response.status}`);
    }

    const data = await response.json();

    return {
      documentId: data.id,
      shareUrl: data.share_url || data.viewer_url
    };
  } catch (err) {
    console.error('Kami upload error:', err);

    // Fallback to local
    const blobUrl = URL.createObjectURL(pdf);
    return {
      documentId: `local_${studentId}_${weekNumber}_${dayNumber}_${Date.now()}`,
      shareUrl: blobUrl,
      isLocal: true
    };
  }
}

/**
 * Get or create Kami document for a submission
 */
export async function getOrCreateKamiDocument(
  studentId: string,
  studentName: string,
  assignmentText: string,
  weekNumber: number,
  dayNumber: number,
  activityQuestion?: string
): Promise<KamiDocument | null> {
  try {
    // Check if document already exists
    const { data: existing } = await supabase
      .from('kami_documents')
      .select('*')
      .eq('student_id', studentId)
      .eq('week_number', weekNumber)
      .eq('day_number', dayNumber)
      .single();

    if (existing) {
      return existing as KamiDocument;
    }

    // Create new Kami document
    const { documentId, shareUrl, isLocal } = await createKamiDocument(
      studentId,
      studentName,
      assignmentText,
      weekNumber,
      dayNumber,
      activityQuestion
    );

    // Don't save local URLs to database (they're temporary)
    if (isLocal) {
      return {
        id: documentId,
        student_id: studentId,
        week_number: weekNumber,
        day_number: dayNumber,
        kami_document_id: documentId,
        kami_share_url: shareUrl,
        created_at: new Date().toISOString()
      };
    }

    // Save to database
    const { data: newDoc, error } = await supabase
      .from('kami_documents')
      .insert({
        student_id: studentId,
        week_number: weekNumber,
        day_number: dayNumber,
        kami_document_id: documentId,
        kami_share_url: shareUrl
      })
      .select()
      .single();

    if (error) {
      console.error('Error saving Kami document:', error);
      return null;
    }

    return newDoc as KamiDocument;
  } catch (err) {
    console.error('Error in getOrCreateKamiDocument:', err);
    return null;
  }
}

/**
 * Open document in Kami or download locally
 */
export function openKamiDocument(shareUrl: string, isLocal?: boolean): void {
  if (isLocal) {
    // For local URLs, trigger download
    const link = document.createElement('a');
    link.href = shareUrl;
    link.download = 'student_submission.pdf';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } else {
    // Open Kami in new window
    window.open(shareUrl, '_blank', 'noopener,noreferrer');
  }
}

/**
 * Get all Kami documents for a teacher's students
 */
export async function getTeacherKamiDocuments(teacherId: string): Promise<KamiDocument[]> {
  try {
    // Get student IDs for this teacher
    const { data: students } = await supabase
      .from('teacher_students')
      .select('student_id')
      .eq('teacher_id', teacherId);

    if (!students || students.length === 0) {
      return [];
    }

    const studentIds = students.map(s => s.student_id);

    // Get Kami documents for those students
    const { data, error } = await supabase
      .from('kami_documents')
      .select('*')
      .in('student_id', studentIds)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching Kami documents:', error);
      return [];
    }

    return (data || []) as KamiDocument[];
  } catch (err) {
    console.error('Error getting teacher Kami documents:', err);
    return [];
  }
}
